USE [master]
GO

/****** Object:  Database [EsportsProject]    Script Date: 9/26/2020 11:16:40 PM ******/
CREATE DATABASE [EsportsProject]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'EsportsProject', FILENAME = N'D:\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\EsportsProject.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'EsportsProject_log', FILENAME = N'D:\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\EsportsProject_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EsportsProject].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [EsportsProject] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [EsportsProject] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [EsportsProject] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [EsportsProject] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [EsportsProject] SET ARITHABORT OFF 
GO

ALTER DATABASE [EsportsProject] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [EsportsProject] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [EsportsProject] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [EsportsProject] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [EsportsProject] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [EsportsProject] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [EsportsProject] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [EsportsProject] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [EsportsProject] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [EsportsProject] SET  DISABLE_BROKER 
GO

ALTER DATABASE [EsportsProject] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [EsportsProject] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [EsportsProject] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [EsportsProject] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [EsportsProject] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [EsportsProject] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [EsportsProject] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [EsportsProject] SET RECOVERY FULL 
GO

ALTER DATABASE [EsportsProject] SET  MULTI_USER 
GO

ALTER DATABASE [EsportsProject] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [EsportsProject] SET DB_CHAINING OFF 
GO

ALTER DATABASE [EsportsProject] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [EsportsProject] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [EsportsProject] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [EsportsProject] SET QUERY_STORE = OFF
GO

ALTER DATABASE [EsportsProject] SET  READ_WRITE 
GO


